### ISSUE TITLE
PRACTICA 4 Y 5

### ISSUE THREAD

**Issue by Alvaro2-0** [SistemasTecTlaxiaco/actividad-8-practica-4y5-lectura-y-escritura-de-un-contrato-sistematosaurias#1]
[PRACTICA 4 Y 5.pdf](https://github.com/SistemasTecTlaxiaco/actividad-8-practica-4y5-lectura-y-escritura-de-un-contrato-sistematosaurias/files/15299681/PRACTICA.4.Y.5.pdf)

**Comment by josealfredo79** [comment]
Bien hecho y revisado...Calificacion 18
